FROM php:8.2-cli

RUN apt-get update && apt-get install -y curl git unzip

RUN echo "memory_limit = 512M" > $PHP_INI_DIR/php.ini

COPY . /myapp
RUN ls -la .
RUN ls -la /root
RUN ls -la /myapp
WORKDIR /myapp

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer require --dev phpunit/phpunit ^9

RUN composer require --dev phpstan/phpstan

ENV PATH="$PATH:/root/.composer/vendor/bin:/myapp/vendor/bin"

CMD ["phpstan", "analyse", "."]