name: CI for PHP App


#Ejecutar en Push/Branch/Main
on:
  push:
    branches:
      - main

#
jobs:
  build:
    runs-on: arc-runner-set

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y curl zstd git
        sudo apt-get install -y libsodium-dev libsodium23 libgd3 libxpm4 libfreetype6-dev libc6-dev bzip2 libpcre3-dev libpcre2-dev
        sudo apt-get install -y fontconfig-config fonts-dejavu-core libdeflate0 libfontconfig1  libjbig0 libtiff5
        sudo ldconfig -p                

    - name: Setup PHP
      uses: shivammathur/setup-php@verbose
      with:
        php-version: 'latest'
        extensions: sodium, curl, pcre, openssl, hash, libxml, mbstring, zip, pcntl, pdo, bcmath, intl, exif, iconv, imagick, json, gd
        tools: phpunit
      continue-on-error: false
      env:
        fail-fast: true

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: composer-${{ hashFiles('composer.lock') }}

    # - name: Install Composer
    #   run: |
    #     curl -sS https://getcomposer.org/installer | php
    #     sudo mv composer.phar /usr/local/bin/composer
  
    # - name: Install PHP dependencies
    #   run: |
    #     composer require --dev phpunit/phpunit

    # - name: Run PHPUnit tests
    #   run: ./vendor/bin/phpunit --configuration phpunit.xml
