name: Dev Workflow Runs

# This workflow runs only if "Dev Workflow" runs
# and do nothing

on:
    workflow_run:
      workflows: 
        - "Dev Workflow"
      types:
        - completed

jobs:
  build:
    runs-on: arc-runner-set

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  