name: CI for PHP App


#Ejecutar en Push/Branch/Main
on:
  push:
    branches:
      - main

#
jobs:
  build:
    runs-on: arc-runner-set

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Install system dependencies
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y \
    #       libxml2-dev \
    #       libssl-dev \
    #       libcurl4-openssl-dev \
    #       libonig-dev \
    #       libpng-dev \
    #       libjpeg-dev \
    #       libfreetype6-dev \
    #       libzip-dev \
    #       zlib1g-dev \
    #       software-properties-common
    #     sudo add-apt-repository ppa:ondrej/php -y
    #     sudo apt-get update

    - name: Setup PHP
      uses: shivammathur/setup-php@verbose
      with:
        php-version: '8.3'
      env:
        debug: true 
        update: true

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
  
    - name: Install dependencies
      run: |
        composer require --dev phpunit/phpunit

    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit --configuration phpunit.xml
