name: Dev Workflow

# This workflow runs only on dev after X other workflows completed
# and do nothing

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: arc-runner-set

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  