name: DevWorkflowRuns

# This workflow runs only if "Dev Workflow" runs
# and does nothing

on:
  workflow_run:
    workflows: 
      - "DevWorkflow"
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest  # Cambia esto a un runner válido

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
