name: CI for PHP App


#Ejecutar en Push/Branch/Main
on:
  push:
    branches:
      - main

#
jobs:
  build:
    runs-on: arc-runner-set

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl zstd

    - name: Setup PHP
      uses: shivammathur/setup-php@verbose
      with:
        php-version: 'latest'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, bcmath, intl, gd, exif, iconv, imagick, json, lz4-kjdev/php-ext-lz4@0.4.3
        tools: phpunit
      env:
        debug: true 
        update: true
    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: composer-${{ hashFiles('composer.lock') }}
        
    - name: Install Composer
      run: |
        sudo apt-get install -y libsodium-dev
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
  
    - name: Install PHP dependencies
      run: |
        composer require --dev phpunit/phpunit

    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit --configuration phpunit.xml
